version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432' # Прокидываем порт наружу
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: filmoteka
    volumes:
      - postgres_data:/var/lib/postgresql/data # Чтобы данные не стерлись при перезапуске контейнера

volumes:
  postgres_data: