### Info
GET http://localhost:3000/api/info

### ===== GENRES =====

### Получить все жанры
GET http://localhost:3000/api/genres

### Получить жанр по ID
GET http://localhost:3000/api/genres/1

### Создать жанр
POST http://localhost:3000/api/genres
Content-Type: application/json

{
  "name": "Документальный"
}

### Обновить жанр
PATCH http://localhost:3000/api/genres/1
Content-Type: application/json

{
  "name": "Боевик/Экшен"
}

### Удалить жанр
DELETE http://localhost:3000/api/genres/1

### Несуществующий жанр (404)
GET http://localhost:3000/api/genres/999

#### add many DON'T WORK
#POST http://localhost:3000/api/genres
#Content-Type: application/json
#
#  ["Боевик",
#  "Комедия",
#  "Драма",
#  "Фантастика",
#  "Ужасы"]